function cost = costFunctionStatic(q,rSdPp,joints0,p,i)
    %% Helper Functions
    FK = Kinematics();
    %% Cost
    roty = @(theta) [cos(theta), 0,sin(theta); ...
              0,1,0; ...
              -sin(theta), 0, cos(theta);
              ];
    cost = norm(rSdPp(:,i) - FK.xe(q,p))  + ... % swing foot desired - swing foot
            + 0.5*trace(eye(3)-FK.R(q,p)) ...
            + 0.5*trace(eye(3)-roty(-pi/2)*FK.RL(q,p)) ...
            + 0.5*trace(eye(3)-roty(-pi/2)*FK.RR(q,p)) + ...
            0.0001*norm(joints0-q);
end